### ISSUE TITLE
Why not make Sliver independent for web-ui?

### ISSUE THREAD

**Issue by pythonSB** [spenceradolph/sliver#1]
For me, the Mythos architecture is very complex and many functions are not used frequently.

**Comment by spenceradolph** [comment]
Sliver at one point had a project dedicated to a GUI. https://github.com/BishopFox/sliver-gui
Unfortunately it got archived.

Mythic isn't actually too bad for hooking into it. Once you have the first couple commands working, the rest are basically copy/pasting off of that. And when Mythic adds cool functionality into the UI, we basically get that for free.

**Comment by pythonSB** [comment]
Thank you for sharing, I will reconstruct webui based on Sliver-py code, it will support multi-node Sliver-server
